//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Healthy HealthResponseStatus = "healthy"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Healthy:
		return true
	default:
		return false
	}
}

// Defines values for LogEntryPriority.
const (
	Alert   LogEntryPriority = "alert"
	Crit    LogEntryPriority = "crit"
	Debug   LogEntryPriority = "debug"
	Emerg   LogEntryPriority = "emerg"
	Err     LogEntryPriority = "err"
	Info    LogEntryPriority = "info"
	Notice  LogEntryPriority = "notice"
	Warning LogEntryPriority = "warning"
)

// Valid indicates whether the value is a known member of the LogEntryPriority enum.
func (e LogEntryPriority) Valid() bool {
	switch e {
	case Alert:
		return true
	case Crit:
		return true
	case Debug:
		return true
	case Emerg:
		return true
	case Err:
		return true
	case Info:
		return true
	case Notice:
		return true
	case Warning:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogsParamsSince.
const (
	GetAppLogsParamsSinceN15m GetAppLogsParamsSince = "15m"
	GetAppLogsParamsSinceN1h  GetAppLogsParamsSince = "1h"
	GetAppLogsParamsSinceN1m  GetAppLogsParamsSince = "1m"
	GetAppLogsParamsSinceN30m GetAppLogsParamsSince = "30m"
	GetAppLogsParamsSinceN3h  GetAppLogsParamsSince = "3h"
	GetAppLogsParamsSinceN5m  GetAppLogsParamsSince = "5m"
)

// Valid indicates whether the value is a known member of the GetAppLogsParamsSince enum.
func (e GetAppLogsParamsSince) Valid() bool {
	switch e {
	case GetAppLogsParamsSinceN15m:
		return true
	case GetAppLogsParamsSinceN1h:
		return true
	case GetAppLogsParamsSinceN1m:
		return true
	case GetAppLogsParamsSinceN30m:
		return true
	case GetAppLogsParamsSinceN3h:
		return true
	case GetAppLogsParamsSinceN5m:
		return true
	default:
		return false
	}
}

// Defines values for GetServiceLogsParamsService.
const (
	Caddy         GetServiceLogsParamsService = "caddy"
	Docker        GetServiceLogsParamsService = "docker"
	Fail2ban      GetServiceLogsParamsService = "fail2ban"
	MithlondAgent GetServiceLogsParamsService = "mithlond-agent"
	NodeExporter  GetServiceLogsParamsService = "node_exporter"
	Ssh           GetServiceLogsParamsService = "ssh"
)

// Valid indicates whether the value is a known member of the GetServiceLogsParamsService enum.
func (e GetServiceLogsParamsService) Valid() bool {
	switch e {
	case Caddy:
		return true
	case Docker:
		return true
	case Fail2ban:
		return true
	case MithlondAgent:
		return true
	case NodeExporter:
		return true
	case Ssh:
		return true
	default:
		return false
	}
}

// Defines values for GetServiceLogsParamsSince.
const (
	GetServiceLogsParamsSinceN15m GetServiceLogsParamsSince = "15m"
	GetServiceLogsParamsSinceN1h  GetServiceLogsParamsSince = "1h"
	GetServiceLogsParamsSinceN1m  GetServiceLogsParamsSince = "1m"
	GetServiceLogsParamsSinceN30m GetServiceLogsParamsSince = "30m"
	GetServiceLogsParamsSinceN3h  GetServiceLogsParamsSince = "3h"
	GetServiceLogsParamsSinceN5m  GetServiceLogsParamsSince = "5m"
)

// Valid indicates whether the value is a known member of the GetServiceLogsParamsSince enum.
func (e GetServiceLogsParamsSince) Valid() bool {
	switch e {
	case GetServiceLogsParamsSinceN15m:
		return true
	case GetServiceLogsParamsSinceN1h:
		return true
	case GetServiceLogsParamsSinceN1m:
		return true
	case GetServiceLogsParamsSinceN30m:
		return true
	case GetServiceLogsParamsSinceN3h:
		return true
	case GetServiceLogsParamsSinceN5m:
		return true
	default:
		return false
	}
}

// AppActionRequest defines model for AppActionRequest.
type AppActionRequest struct {
	AppSlug     string `json:"app_slug"`
	Environment string `json:"environment"`
}

// AppActionResponse defines model for AppActionResponse.
type AppActionResponse struct {
	Message *string `json:"message,omitempty"`
	Output  *string `json:"output,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// CreateBinaryAppRequest defines model for CreateBinaryAppRequest.
type CreateBinaryAppRequest struct {
	AppId           string             `json:"app_id"`
	AppSlug         string             `json:"app_slug"`
	ArtifactName    string             `json:"artifact_name"`
	ArtifactSource  string             `json:"artifact_source"`
	ArtifactVersion string             `json:"artifact_version"`
	CallbackUrl     string             `json:"callback_url"`
	DeploymentId    string             `json:"deployment_id"`
	Domain          string             `json:"domain"`
	EnvVars         *map[string]string `json:"env_vars,omitempty"`
	EnvironmentName string             `json:"environment_name"`
	HealthcheckUrl  *string            `json:"healthcheck_url,omitempty"`
	Port            int                `json:"port"`
	TeamSlug        string             `json:"team_slug"`
}

// CreateDockerAppRequest defines model for CreateDockerAppRequest.
type CreateDockerAppRequest struct {
	AppId   string `json:"app_id"`
	AppSlug string `json:"app_slug"`

	// ArtifactSource Docker image reference without the tag (e.g. `registry.example.com/myapp`).
	ArtifactSource string `json:"artifact_source"`

	// ArtifactVersion Docker image tag (e.g. `v1.2.3`).
	ArtifactVersion string             `json:"artifact_version"`
	CallbackUrl     string             `json:"callback_url"`
	DeploymentId    string             `json:"deployment_id"`
	DockerCommand   *[]string          `json:"docker_command,omitempty"`
	Domain          string             `json:"domain"`
	EnvVars         *map[string]string `json:"env_vars,omitempty"`
	EnvironmentName string             `json:"environment_name"`
	Port            int                `json:"port"`
	Ports           *[]string          `json:"ports,omitempty"`
	TeamSlug        string             `json:"team_slug"`
	Volumes         *[]string          `json:"volumes,omitempty"`
}

// DeployBinaryAppRequest defines model for DeployBinaryAppRequest.
type DeployBinaryAppRequest struct {
	AppId           string             `json:"app_id"`
	AppSlug         string             `json:"app_slug"`
	Args            *[]string          `json:"args,omitempty"`
	ArtifactName    string             `json:"artifact_name"`
	ArtifactSource  string             `json:"artifact_source"`
	ArtifactVersion string             `json:"artifact_version"`
	CallbackUrl     string             `json:"callback_url"`
	DeploymentId    string             `json:"deployment_id"`
	EnvVars         *map[string]string `json:"env_vars,omitempty"`
	EnvironmentName string             `json:"environment_name"`
	TeamSlug        string             `json:"team_slug"`
}

// DeployDockerAppRequest defines model for DeployDockerAppRequest.
type DeployDockerAppRequest struct {
	AppId   string `json:"app_id"`
	AppSlug string `json:"app_slug"`

	// ArtifactSource Docker image reference without the tag (e.g. `registry.example.com/myapp`).
	ArtifactSource string `json:"artifact_source"`

	// ArtifactVersion Docker image tag (e.g. `v1.2.3`).
	ArtifactVersion string             `json:"artifact_version"`
	CallbackUrl     string             `json:"callback_url"`
	DeploymentId    string             `json:"deployment_id"`
	EnvVars         *map[string]string `json:"env_vars,omitempty"`
	EnvironmentName string             `json:"environment_name"`
	TeamSlug        string             `json:"team_slug"`
}

// DeployResponse defines model for DeployResponse.
type DeployResponse struct {
	Logs    *string `json:"logs,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// GenericObject defines model for GenericObject.
type GenericObject map[string]interface{}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  HealthResponseStatus `json:"status"`
	Version string               `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// LogEntry defines model for LogEntry.
type LogEntry struct {
	// Message The log message content.
	Message string `json:"message"`

	// Priority Syslog severity level.
	Priority *LogEntryPriority `json:"priority,omitempty"`

	// Timestamp ISO 8601 timestamp of the log entry.
	Timestamp time.Time `json:"timestamp"`
}

// LogEntryPriority Syslog severity level.
type LogEntryPriority string

// LogsResponse defines model for LogsResponse.
type LogsResponse struct {
	Entries []LogEntry `json:"entries"`
	Service string     `json:"service"`
}

// UpdateAgentRequest defines model for UpdateAgentRequest.
type UpdateAgentRequest struct {
	ArtifactVersion        string  `json:"artifact_version"`
	OverrideArtifactSource *string `json:"override_artifact_source,omitempty"`
}

// UpdateAgentResponse defines model for UpdateAgentResponse.
type UpdateAgentResponse struct {
	Message *string `json:"message,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// GetAppLogsParams defines parameters for GetAppLogs.
type GetAppLogsParams struct {
	TeamSlug        string `form:"team_slug" json:"team_slug"`
	AppId           string `form:"app_id" json:"app_id"`
	AppSlug         string `form:"app_slug" json:"app_slug"`
	EnvironmentName string `form:"environment_name" json:"environment_name"`

	// Since How far back to fetch logs. Capped at 3 hours.
	Since *GetAppLogsParamsSince `form:"since,omitempty" json:"since,omitempty"`
}

// GetAppLogsParamsSince defines parameters for GetAppLogs.
type GetAppLogsParamsSince string

// GetServiceLogsParams defines parameters for GetServiceLogs.
type GetServiceLogsParams struct {
	// Service The systemd service unit to fetch logs for.
	Service GetServiceLogsParamsService `form:"service" json:"service"`

	// Since How far back to fetch logs. Capped at 3 hours.
	Since *GetServiceLogsParamsSince `form:"since,omitempty" json:"since,omitempty"`
}

// GetServiceLogsParamsService defines parameters for GetServiceLogs.
type GetServiceLogsParamsService string

// GetServiceLogsParamsSince defines parameters for GetServiceLogs.
type GetServiceLogsParamsSince string

// UpdateAgentJSONRequestBody defines body for UpdateAgent for application/json ContentType.
type UpdateAgentJSONRequestBody = UpdateAgentRequest

// CreateBinaryAppJSONRequestBody defines body for CreateBinaryApp for application/json ContentType.
type CreateBinaryAppJSONRequestBody = CreateBinaryAppRequest

// CreateDockerAppJSONRequestBody defines body for CreateDockerApp for application/json ContentType.
type CreateDockerAppJSONRequestBody = CreateDockerAppRequest

// DeployBinaryAppJSONRequestBody defines body for DeployBinaryApp for application/json ContentType.
type DeployBinaryAppJSONRequestBody = DeployBinaryAppRequest

// DeployDockerAppJSONRequestBody defines body for DeployDockerApp for application/json ContentType.
type DeployDockerAppJSONRequestBody = DeployDockerAppRequest

// RestartAppJSONRequestBody defines body for RestartApp for application/json ContentType.
type RestartAppJSONRequestBody = AppActionRequest

// StartAppJSONRequestBody defines body for StartApp for application/json ContentType.
type StartAppJSONRequestBody = AppActionRequest

// StopAppJSONRequestBody defines body for StopApp for application/json ContentType.
type StopAppJSONRequestBody = AppActionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Update agent binary
	// (POST /agent/update)
	UpdateAgent(w http.ResponseWriter, r *http.Request)
	// Create binary app (install and start)
	// (POST /app/create/binary)
	CreateBinaryApp(w http.ResponseWriter, r *http.Request)
	// Create docker app (install and start)
	// (POST /app/create/docker)
	CreateDockerApp(w http.ResponseWriter, r *http.Request)
	// Deploy binary app (update and restart)
	// (POST /app/deploy/binary)
	DeployBinaryApp(w http.ResponseWriter, r *http.Request)
	// Deploy docker app (update and restart)
	// (POST /app/deploy/docker)
	DeployDockerApp(w http.ResponseWriter, r *http.Request)
	// Restart app service
	// (POST /app/restart)
	RestartApp(w http.ResponseWriter, r *http.Request)
	// Start app service
	// (POST /app/start)
	StartApp(w http.ResponseWriter, r *http.Request)
	// Stop app service
	// (POST /app/stop)
	StopApp(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Get logs for a specific app environment
	// (GET /v1/app/logs)
	GetAppLogs(w http.ResponseWriter, r *http.Request, params GetAppLogsParams)
	// Get systemd journal logs for a server-level service
	// (GET /v1/logs)
	GetServiceLogs(w http.ResponseWriter, r *http.Request, params GetServiceLogsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UpdateAgent operation middleware
func (siw *ServerInterfaceWrapper) UpdateAgent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBinaryApp operation middleware
func (siw *ServerInterfaceWrapper) CreateBinaryApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBinaryApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDockerApp operation middleware
func (siw *ServerInterfaceWrapper) CreateDockerApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDockerApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployBinaryApp operation middleware
func (siw *ServerInterfaceWrapper) DeployBinaryApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployBinaryApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployDockerApp operation middleware
func (siw *ServerInterfaceWrapper) DeployDockerApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployDockerApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestartApp operation middleware
func (siw *ServerInterfaceWrapper) RestartApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestartApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartApp operation middleware
func (siw *ServerInterfaceWrapper) StartApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopApp operation middleware
func (siw *ServerInterfaceWrapper) StopApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppLogs operation middleware
func (siw *ServerInterfaceWrapper) GetAppLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAppLogsParams

	// ------------- Required query parameter "team_slug" -------------

	if paramValue := r.URL.Query().Get("team_slug"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "team_slug"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "team_slug", r.URL.Query(), &params.TeamSlug, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_slug", Err: err})
		return
	}

	// ------------- Required query parameter "app_id" -------------

	if paramValue := r.URL.Query().Get("app_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "app_id"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "app_id", r.URL.Query(), &params.AppId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	// ------------- Required query parameter "app_slug" -------------

	if paramValue := r.URL.Query().Get("app_slug"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "app_slug"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "app_slug", r.URL.Query(), &params.AppSlug, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_slug", Err: err})
		return
	}

	// ------------- Required query parameter "environment_name" -------------

	if paramValue := r.URL.Query().Get("environment_name"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "environment_name"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "environment_name", r.URL.Query(), &params.EnvironmentName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "environment_name", Err: err})
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetServiceLogs operation middleware
func (siw *ServerInterfaceWrapper) GetServiceLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServiceLogsParams

	// ------------- Required query parameter "service" -------------

	if paramValue := r.URL.Query().Get("service"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "service"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "service", r.URL.Query(), &params.Service, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service", Err: err})
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServiceLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/agent/update", wrapper.UpdateAgent)
	m.HandleFunc("POST "+options.BaseURL+"/app/create/binary", wrapper.CreateBinaryApp)
	m.HandleFunc("POST "+options.BaseURL+"/app/create/docker", wrapper.CreateDockerApp)
	m.HandleFunc("POST "+options.BaseURL+"/app/deploy/binary", wrapper.DeployBinaryApp)
	m.HandleFunc("POST "+options.BaseURL+"/app/deploy/docker", wrapper.DeployDockerApp)
	m.HandleFunc("POST "+options.BaseURL+"/app/restart", wrapper.RestartApp)
	m.HandleFunc("POST "+options.BaseURL+"/app/start", wrapper.StartApp)
	m.HandleFunc("POST "+options.BaseURL+"/app/stop", wrapper.StopApp)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/v1/app/logs", wrapper.GetAppLogs)
	m.HandleFunc("GET "+options.BaseURL+"/v1/logs", wrapper.GetServiceLogs)

	return m
}
